#ifndef CLIENT_H
#define CLIENT_H
#include <openssl/sha.h>
#include <arpa/inet.h>
#include <iostream>
#include <netinet/in.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>
#include <netdb.h>
#include <thread>
#include <vector>
#include <istream>
#include <iostream>
#include <vector>
#include <string>
#include <sstream>
#include <iterator>
#endif
